// Bosnian-language strings.
// BS_LABELS / BS_DEFAULTS: shown on form labels and printed output (match the source documents).
// UI_LABELS: shown in the screen UI (nav, buttons, modals, page titles).
// Single-locale app — every visible string lives here.

const BS_LABELS = {
  paletaBroj: "Paleta broj:",
  proizvodjac: "Proizvođač :",
  vetKontrolniBroj: "Veterinarski kontrolni broj  izvoznog objekta:",
  vetOznaka: "Veterinarska oznaka No.:",
  vetOznakaShort: "Veterinarska no.",
  primatelj: "Primatelj / Uvoznik:",
  porijekloUzgoja: "Porijeklo uzgoja:",
  datumProizvodnje: "Datum proizvodnje:",
  najboljeUpotrijebiti: "Najbolje upotrijebiti do:",
  potrebnaTemperatura: "Potrebna temperatura\nskladištenja i transporta",
  ukupnoBlokova: "Ukupno blokova",
  netoTezina: "Neto težina kg:",
  tezinaPalete: "Težina palete :",
  tezinaPaleteKaveza: "Težina palete/kaveza :",
  brutoTezina: "Bruto težina:",
  hemijskaAnaliza: "HEMIJSKA ANALIZA % :",
  mast: "MAST",
  protein: "PROTEIN",
  vlaga: "VLAGA"
};

const BS_DEFAULTS = {
  producerName: "BROVIS DD VISOKO",
  producerAddress: "Dobrinje bb, Visoko, Bosna i Hercegovina",
  producerVetControl: "2-116",
  recipient: "OVAKO d.o.o Mostarsko raskršće bb  Sarajevo",
  place: "Visoko"
};

const UI_LABELS = {
  // App-wide
  appName: "Brovis - deklaracije paleta",
  // Nav
  dashboard: "Start",
  settings: "Postavke",
  types: "Tipovi dokumenata",
  back: "Nazad",
  install: "Instaliraj",
  // Document actions
  newDocument: "Novi dokument",
  editDocument: "Uredi dokument",
  save: "Sačuvaj",
  saveAndPrint: "Sačuvaj i štampaj",
  cancel: "Otkaži",
  delete: "Obriši",
  edit: "Uredi",
  print: "Štampaj",
  printSelected: "Štampaj odabrane",
  printNext: "Štampaj sljedeći",
  deleteSelected: "Obriši odabrane",
  confirm: "Potvrdi",
  ok: "U redu",
  close: "Zatvori",
  // Search / sort
  search: "Pretraga",
  searchPlaceholder: "Pretraga: paleta, vet. oznaka, porijeklo…",
  productionFrom: "Proizvodnja od",
  productionTo: "Proizvodnja do",
  sort: "Sortiraj",
  sortNewest: "Najnovije prvo",
  sortOldest: "Najstarije prvo",
  sortProdDesc: "Datum proizvodnje ↓",
  sortProdAsc: "Datum proizvodnje ↑",
  sortPaletaAsc: "Paleta broj ↑",
  sortPaletaDesc: "Paleta broj ↓",
  selectedCount: (n) => `${n} odabrano`,
  // Empty / status messages
  emptyNoDocs: "Nema dokumenata. Pritisnite + za novi.",
  emptyNoMatch: "Nema dokumenata koji odgovaraju filterima.",
  emptyNoTypes: "Nema tipova dokumenata. ",
  createOne: "Dodajte tip",
  // Form sections
  sectionPallet: "Paleta",
  sectionProducer: "Proizvođač",
  sectionProduct: "Proizvod",
  sectionDates: "Datumi",
  sectionStorage: "Skladištenje",
  sectionChemical: "Hemijska analiza",
  sectionFooter: "Podnožje",
  // Form fields (English-ish in code, Bosnian in label)
  fieldPaletaBroj: "Paleta broj",
  fieldProducerName: "Naziv",
  fieldProducerAddress: "Adresa",
  fieldVetControl: "Veterinarski kontrolni broj",
  fieldType: "Tip",
  fieldRecipient: "Primatelj / Uvoznik",
  fieldVetMark: "Veterinarska oznaka No.",
  fieldOrigin: "Porijeklo uzgoja",
  fieldProductionDate: "Datum proizvodnje",
  fieldBestBefore: "Najbolje upotrijebiti do",
  fieldTemperature: "Temperatura",
  fieldTotalBlocks: "Ukupno blokova",
  fieldNetWeight: "Neto težina (kg)",
  fieldPalletWeight: "Težina palete (kg)",
  fieldPalletCageWeight: "Težina palete/kaveza (kg)",
  fieldGrossWeight: "Bruto težina (kg)",
  fieldFat: "MAST %",
  fieldProtein: "PROTEIN %",
  fieldMoisture: "VLAGA %",
  fieldPlace: "Mjesto",
  fieldDate: "Datum",
  manualOverride: "Ručno",
  hintPaletaBroj: "Predloženi sljedeći broj za ovaj tip.",
  // Settings sections / labels
  producerDefaults: "Standardne vrijednosti proizvođača",
  saveProducerDefaults: "Sačuvaj standardne vrijednosti",
  defaultRecipientPlace: "Standardni primatelj i mjesto",
  defaultRecipient: "Standardni primatelj",
  defaultPlace: "Standardno mjesto",
  saveDefaults: "Sačuvaj",
  theme: "Tema",
  themeAuto: "Automatski",
  themeLight: "Svijetla",
  themeDark: "Tamna",
  storage: "Memorija",
  storageCalculating: "Računam…",
  storageUsage: (mb, gb, pct) => `Iskorišteno ${mb} MB od ${gb} GB dostupno (${pct}%).`,
  storageNoApi: "Pregled memorije nije dostupan u ovom browseru.",
  storageOver80: "Iskorištenje memorije preko 80%. Napravi backup i razmotri brisanje starih dokumenata.",
  dataManagement: "Upravljanje podacima",
  exportDesc: "Sačuvaj sve podatke u JSON datoteku.",
  exportAll: "Izvezi sve",
  importDesc: "Učitaj backup iz JSON datoteke.",
  importBtn: "Uvezi…",
  lastExport: (d) => `Posljednji izvoz: ${d}`,
  noExports: "Još nema izvoza.",
  deleteAllData: "Obriši sve podatke",
  deleteAllDataDesc: "Trajno briše svaki dokument, tip i postavku.",
  // Types screen
  addNewType: "Dodaj novi tip",
  typeTitle: "Naslov (dozvoljen je prelom u novi red)",
  typeTemperature: "Standardna temperatura",
  typeShelfLife: "Rok trajanja (dani)",
  typeRequiresChem: "Zahtijeva hemijsku analizu",
  typeWeightLabel: "Oznaka za težinu",
  typeWeightPalete: "Težina palete",
  typeWeightPaleteKaveza: "Težina palete/kaveza",
  newType: "Novi tip",
  editType: "Uredi tip",
  // Documents table headers
  thPallet: "Paleta broj",
  thVet: "Vet. oznaka",
  thProduction: "Proizvodnja",
  thNet: "Neto kg",
  thActions: "Radnje",
  thChem: "Hemijska",
  thWeightLabel: "Oznaka težine",
  thDocs: "Dokumenti",
  // Modals
  modalDiscardTitle: "Odbaciti izmjene?",
  modalDiscardBody: "Vaše izmjene će biti izgubljene.",
  modalDiscard: "Odbaci",
  modalDeleteDocTitle: "Obriši dokument",
  modalDeleteDocBody: (broj) => `Obrisati paletu ${broj}? Radnja se ne može poništiti.`,
  modalDeleteSelTitle: "Obriši odabrane",
  modalDeleteSelBody: (n) => `Obrisati ${n} dokument(a)? Radnja se ne može poništiti.`,
  modalDeleteAllOfTypeTitle: "Obriši sve dokumente ovog tipa",
  modalDeleteAllOfTypeBody: (title, n) => `Trajno brisanje svih ${n} dokument(a) tipa "${title}". Radnja se ne može poništiti.`,
  modalDeleteAllDataTitle: "Obriši sve podatke",
  modalDeleteAllDataBody: "Ovo trajno briše svaki dokument, tip i postavku na ovom uređaju. Nastaviti?",
  modalDeleteTypeTitle: "Obriši tip",
  modalDeleteTypeBody: (title) => `Obrisati tip "${title}"?`,
  modalCannotDeleteTitle: "Ne može se obrisati",
  modalCannotDeleteBody: (n) => `Ovaj tip ima ${n} dokument(a). Prvo ih obrišite ili preraspodijelite.`,
  // Import
  modalImportTitle: "Uvoz backupa",
  modalImportBody: (docs, types) => `Pronađeno ${docs} dokument(a) i ${types} tip(ova). Kako ih primijeniti?`,
  importMerge: "Spoji po ID-u",
  importReplace: "Zamijeni sve",
  importFailedTitle: "Uvoz neuspješan",
  importFailedJson: "Datoteka nije validan JSON.",
  importFailedShape: "Datoteka ne izgleda kao Brovis backup.",
  importDone: "Uvoz završen",
  importDoneBody: "Backup uvezen.",
  // Toasts / banners
  toastProducerSaved: "Standardne vrijednosti proizvođača sačuvane.",
  toastDefaultsSaved: "Standardne vrijednosti sačuvane.",
  toastBackupDownloaded: "Backup preuzet.",
  bannerUpdateAvailable: "Dostupno je ažuriranje.",
  bannerReload: "Učitaj ponovo",
  bannerBackupReminder: (days) => `Preporučen je backup. Posljednji izvoz: prije ${days} dan(a).`,
  bannerExportNow: "Izvezi sada",
  // Counts
  docsAcross: (docs, types) => `Svaki tip dokumenta predstavlja jedan proizvod. Trenutno: ${docs} dokument(a) u ${types} tip(ova).`,
  docsCount: (n) => `${n} dokument(a)`,
  typesCount: (n) => `Tipovi dokumenata predstavljaju proizvode. Ukupno: ${n} tip(ova).`,
  // Form errors
  errFormHeader: "Provjerite obavezna polja:",
  errPaletaBroj: "Paleta broj je obavezan",
  errProductionDate: "Datum proizvodnje je obavezan",
  errBestBefore: "Datum najbolje upotrijebiti je obavezan",
  errNetWeight: "Neto težina je obavezna",
  errPalletWeight: "Težina palete je obavezna",
  errTotalBlocks: "Ukupno blokova je obavezno",
  errTemperature: "Temperatura je obavezna",
  errVetMark: "Veterinarska oznaka je obavezna",
  errOriginOfBreeding: "Porijeklo uzgoja je obavezno",
  errRecipient: "Primatelj je obavezan"
};

window.BS_LABELS = BS_LABELS;
window.BS_DEFAULTS = BS_DEFAULTS;
window.UI_LABELS = UI_LABELS;
